title: My Awesome Home
views:
  # View tab title.
  - title: Highlights
    icon: mdi:home
    cards:
      - type: entity
        entity: input_number.mailboxfull
        icon: mdi:mailbox
        name: Post Box
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.temperature_setpoint_living
            name: set temp living
          - type: sensor
            entity: sensor.temperature_living
            name: temperature living
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.temperature_setpoint_zolder
            name: set temp zolder
          - type: sensor
            entity: sensor.temperature_zolder_vaillant
            name: temperature zolder
      - type: horizontal-stack
        cards:
          - type: entity
            entity: sensor.solaredge_energy_today
            unit: Wh
            name: Solar Energy today
          - type: gauge
            entity: sensor.solaredge_current_power
            name: Solar power
            min: 0
            max: 3000
  - title: Heating
    icon: mdi:radiator
    cards:
      - type: entities
        title: Living
        entities:
          - sensor.temperature_setpoint_living
          - sensor.temperature_living
          - input_boolean.turn_heating_on
          - input_number.slider_day
          - input_number.slider_night
          - input_number.slider1
          - sensor.temperature_flow_radiator
          - sensor.temperature_flow
      - type: entities
        title: Zolder
        entities:
          - sensor.temperature_setpoint_zolder
          - sensor.temperature_zolder_vaillant
          - input_boolean.work_from_home
          - input_boolean.turn_heating_zolder_on
          - input_number.slider_floor_day
          - input_number.slider_floor_night
          - input_number.slider_floor_now
          - sensor.temperature_setp_flow_zolder
          - sensor.temperature_flow_zolder
          - sensor.pressure_boiler
          - entity: switch.s26_control
            name: "heating 2nd room"
      - type: history-graph
        title: "heater setpunt"
        entities:
          - sensor.temperature_flow_radiator
        hours_to_show: 72
        refresh_interval: 600
  - title: switches
    icon: mdi:toggle-switch
    cards:
      - type: entities
        title: Zolder
        entities:
          - entity: switch.s26_b
            name: Mollen
          - entity: switch.athom_2
            name: zolder desk
          - entity: switch.balco_1
            name: stereo - waterkoker
          - entity: switch.ventilator_control
            name: 3d printer
      - type: entities
        title: Living
        entities:
          - entity: switch.balco_2
            name: TV
          - entity: switch.s20_control
            name: muur
      - type: entities
        title: Garage
        entities:
          - entity: switch.athom_car
            name: car charger
      - type: entities
        title: athom car
        entities:
          - sensor.car_energy_today
          - sensor.car_power
          - sensor.car_total_energy
      - type: entities
        title: athom 2
        entities:
          - sensor.athom2_energy_today
          - sensor.athom2_power
          - sensor.athom2_total_energy
  - title: Temperatures
    icon: mdi:thermometer
    cards:
      - type: entities
        title: Temperatures
        entities:
          - sensor.temperature_buiten_vaillant
          - sensor.temperature_living
          - sensor.temperature_bathroom
          - entity: sensor.temperature_slaapkamer
            name: temperature keuken
          - entity: sensor.temperature_zolder
            name: temperature zolder alarm
          - sensor.temperature_zolder_vaillant
          - sensor.zoldernok_temp
      - type: history-graph
        title: "living temperature"
        entities:
          - sensor.temperature_setpoint_living
          - sensor.temperature_living
        hours_to_show: 72
        refresh_interval: 600
      - type: history-graph
        title: "temp kamers"
        entities:
          - sensor.temperature_bathroom
          - sensor.temperature_slaapkamer
        hours_to_show: 72
        refresh_interval: 600
      - type: sensor
        entity: sensor.temperature_living
        graph: line
        detail: 2
        hours_to_show: 72
      - type: sensor
        entity: sensor.temperature_zolder
        graph: line
        detail: 2
        hours_to_show: 72
  - title: Weather
    icon: mdi:weather-sunny
    cards:
      # The markdown card will render markdown text.
      - type: entities
        title: Weersvoorspelling
        entities:
          - sensor.br_detailed_condition
          - sensor.br_ground_temperature
          - sensor.br_temperature
          - sensor.br_precipitation
          - sensor.br_precipitation_forecast_average
          - sensor.br_rain_1d
          - sensor.br_wind_speed
          - sensor.br_wind_direction
          - sensor.br_pressure
      - type: iframe
        url: https://weerdata.weerslag.nl/image/1.0/?size=ani-forecast-550x550&type=Freecontent&v=14487341
        aspect_ratio: 100%
        title: Buien
      - type: iframe
        url: https://pollennieuws.nl/weerkaart/be-320kaart-website.png
        aspect_ratio: 100%
        title: Pollen
  - title: lights
    icon: mdi:lightbulb
    cards:
      - type: entities
        title: Living
        entities:
          - light.tradfri_bulb_2
          - light.tradfri_bulb_3
          - light.tradfri_bulb_5
          - light.tradfri_bulb_8
      - type: entities
        title: buitenverlichting
        entities:
          - switch.verlichting_terras_1
          - switch.verlichting_terras_2
          - switch.opritverlichting
      - type: entities
        title: zolderverlichting
        entities:
          - switch.zolder_licht
  - title: robot
    icon: mdi:ladybug
    cards:
      - type: vertical-stack
        title: Gras robot
        cards:
          - type: entities
            title: Gras robot control
            entities:
              - binary_sensor.robot_status
              - switch.robomow_control
          - type: entities
            title: Energy and power
            entities:
              - sensor.robot_energy_today
              - sensor.robot_total_energy
              - sensor.robot_energy_start
              - sensor.robot_power
          - type: history-graph
            title: "Power"
            entities:
              - sensor.robot_power
            hours_to_show: 72
            refresh_interval: 600
          - type: history-graph
            title: "Energy"
            entities:
              - sensor.robot_total_energy
            hours_to_show: 72
            refresh_interval: 600
      - type: vertical-stack
        title: Vacuum
        cards:
          - type: entities
            entities:
              - switch.fluffie_schedule
              - sensor.fluffie_battery
          - type: picture-entity
            entity: camera.fluffie_cleaning_map
  - title: media
    icon: mdi:television-classic
    cards:
      - type: media-control
        entity: media_player.living_room_main
      - type: entities
        title: Bluetooth speaker
        entities:
          - input_boolean.start_bluetooth_speaker
          - input_boolean.pause_bluetooth_speaker
          - input_boolean.resume_bluetooth_speaker
      - type: media-control
        entity: media_player.living_room_tv
  - title: commute
    icon: mdi:car
    cards:
      - type: entities
        entities:
          - sensor.commute
      - type: entities
        title: Car electricity
        entities:
          - sensor.car_energy_today
          - sensor.car_power
          - sensor.car_total_energy
  - title: Presence
    icon: mdi:human-male-female
    cards:
      - type: glance
        title: aanwezigheid
        entities:
          - binary_sensor.alarm_state
      - type: glance
        title: Post
        entities:
          - input_number.mailboxfull
          - sensor.mailbox
  - title: humidity
    icon: mdi:water-percent
    cards:
      - type: entities
        title: humidity
        entities:
          - sensor.humidity_zolder
          - sensor.humidity_bathroom
          - entity: sensor.humidity_slaapkamer
            name: humidity keuken
      - type: entities
        title: water level
        entities:
          - sensor.water_level_bus_voltage
          - sensor.water_level_depth
          - sensor.water_level_depth_2
      - type: history-graph
        title: "water level"
        entities:
          - sensor.water_level_depth
          - sensor.water_level_depth_2
        hours_to_show: 8760
        refresh_interval: 600
      - type: history-graph
        title: "measured air pressure"
        entities:
          - sensor.air_pressure
        hours_to_show: 8760
        refresh_interval: 600
      - type: history-graph
        title: "shunt voltage ina219"
        entities:
          - sensor.water_level_shunt
        hours_to_show: 8760
        refresh_interval: 600
  - title: zon
    icon: mdi:solar-panel
    cards:
      - type: entities
        title: energy
        entities:
          - sensor.solaredge_energy_today
          - sensor.solaredge_energy_this_month
          - sensor.solaredge_energy_this_year
      - type: entities
        title: inverter
        entities:
          - sensor.solaredge_current_power
          - sensor.solaredge_energy_today
      - type: history-graph
        title: "solar power"
        entities:
          - sensor.solaredge_current_power
        hours_to_show: 168
        refresh_interval: 600
      - type: history-graph
        title: "solar energy"
        entities:
          - sensor.solaredge_energy_today
        hours_to_show: 8760
        refresh_interval: 600
      - type: history-graph
        title: "wind voltage"
        entities:
          - sensor.wind_voltage
        hours_to_show: 72
        refresh_interval: 20
      - type: history-graph
        title: "wind torque setp"
        entities:
          - sensor.wind_torque_setp
        hours_to_show: 1
        refresh_interval: 20
      - type: entities
        title: wind
        entities:
          - sensor.wind_rotational_speed
          - sensor.wind_power
          - sensor.wind_voltage
          - sensor.wind_torque_setp
          - sensor.wind_message_counter
  - title: k8400
    icon: mdi:printer-3d
    cards:
      - type: iframe
        url: http://192.168.0.209:8080/?action=stream
        aspect_ratio: 100%
      - type: entity
        entity: input_number.k8400_state
        name: 3d printer
      - type: horizontal-stack
        cards:
          - type: entity
            entity: input_number.k8400_printtime_elapsed
            name: time elapsed
          - type: entity
            entity: input_number.k8400_printtime_left
            name: time left
      - type: horizontal-stack
        cards:
          - type: entity
            entity: input_number.k8400_tool0_temperature
            name: temp extruder 1
          - type: entity
            entity: input_number.k8400_bed_temperature
            name: temp bed
      - type: horizontal-stack
        cards:
          - type: entities
            entities:
              - input_select.led_printer
              - input_boolean.print_cancel
              - input_boolean.print_pause_cyclic
