title: My Awesome Home
views:
    # View tab title.
  - title: Heating
    icon: mdi:radiator
    cards:
      - type: entities
        title: Living
        entities:
          - sensor.temperature_setpoint_living
          - sensor.temperature_living
          - input_boolean.turn_heating_on
          - switch.ventilator_control
          - input_number.slider_day
          - input_number.slider_night
          - input_number.slider1
          - sensor.temperature_flow_radiator
      - type: entities
        title: Badkamer
        entities:
          - binary_sensor.heater_status
          - switch.handdoekdroger_control
      - type: entities
        title: automations
        entities:
          - automation.handdoekdroger_automatisch
          - automation.start_ventilator_radiator
          - automation.stop_ventilator_radiator
          - automation.heating_off_when_turning_alarm_on
          - automation.heating_on_when_turning_alarm_off
          - automation.read_ebus
  #        - automation.set_temp_high_when_being_home_weekend
  #        - automation.set_temp_high_when_being_home_workday
          - automation.set_temp_low_when_leaving_house
          - automation.wakup_turn_heating_up_weekday
          - automation.wakup_turn_heating_up_saturday
          - automation.wakup_turn_heating_up_sunday
      - type: history-graph
        title: 'heater setpunt'
        entities:
          - sensor.temperature_flow_radiator
        hours_to_show: 72
        refresh_interval: 600
  - title: Temperatures
    icon: mdi:thermometer
    cards:
      - type: entities
        title: Temperatures
        entities:
          - sensor.temperature_living
          - sensor.temperature_bathroom
          - sensor.temperature_slaapkamer
          - sensor.temperature_zolder
      - type: history-graph
        title: 'living temperature'
        entities:
          - sensor.temperature_setpoint_living
          - sensor.temperature_living
        hours_to_show: 72
        refresh_interval: 600
      - type: history-graph
        title: 'temp kamers'
        entities:
          - sensor.temperature_bathroom
          - sensor.temperature_slaapkamer
        hours_to_show: 72
        refresh_interval: 600
      - type: history-graph
        title: 'temp zolder'
        entities:
          - sensor.temperature_zolder
        hours_to_show: 72
        refresh_interval: 600
  - title: Weather
    icon: mdi:weather-sunny
    cards:
        # The markdown card will render markdown text.
      - type: entities
        title: Weersvoorspelling
        entities:
          - sensor.br_detailed_condition
          - sensor.br_ground_temperature
          - sensor.br_temperature
          - sensor.br_precipitation
          - sensor.br_precipitation_forecast_average
          - sensor.br_rain_1d
          - sensor.br_wind_speed
          - sensor.br_wind_direction
      - type: iframe
        url: https://weerdata.weerslag.nl/image/1.0/?size=ani-forecast-550x550&type=Freecontent&v=14487341
        aspect_ratio: 140%
        title: Buien
  - title: gras robot
    icon: mdi:ladybug
    cards:
      - type: entities
        title: Gras robot control
        entities:
          - binary_sensor.robot_status
          - switch.robomow_control
      - type: entities
        title: Energy and power
        entities:
          - sensor.robot_energy_today
          - sensor.robot_total_energy
          - sensor.robot_energy_start
          - sensor.robot_power
      - type: history-graph
        title: 'Power'
        entities:
          - sensor.robot_power
        hours_to_show: 72
        refresh_interval: 600
      - type: history-graph
        title: 'Energy'
        entities:
          - sensor.robot_total_energy
        hours_to_show: 72
        refresh_interval: 600
  - title: switches
    icon: mdi:toggle-switch
    cards:
      - type: entities
        title: schakelaars
        entities:
          - switch.s20_control
          - switch.s26_control
  - title: Presence
    icon: mdi:human-male-female
    cards:
      - type: glance
        title: aanwezigheid
        entities:
          - device_tracker.7c_7d_3d_ba_ef_be
          - device_tracker.motorolla_stijn
          - binary_sensor.alarm_state
  - title: humidity
    icon: mdi:water-percent
    cards:
      - type: entities
        title: humidity
        entities:
          - sensor.humidity_zolder
          - sensor.humidity_bathroom
          - sensor.humidity_slaapkamer
  - title: media
    icon: mdi:television-classic
    cards:
      - type: media-control
        entity: media_player.kodi_libreelec_local
      - type: media-control
        entity: media_player.living_main
  - title: commute
    icon: mdi:car
    cards:
      - type: entities
        entities:
          - sensor.commute
