title: My Awesome Home
theme: dark-mode
views:
    # View tab title.
  - title: Weather
    cards:
        # The markdown card will render markdown text.
      - type: entities
        title: Weersvoorspelling
        entities:
          - sensor.br_detailed_condition
          - sensor.br_ground_temperature
          - sensor.br_temperature
          - sensor.br_precipitation
          - sensor.br_precipitation_forecast_average
          - sensor.br_rain_1d
          - sensor.br_wind_speed
          - sensor.br_wind_direction
      - type: iframe
        url: https://weerdata.weerslag.nl/image/1.0/?size=ani-forecast-550x550&type=Freecontent&v=14487341
        aspect_ratio: 140%
        title: Buien
  - title: Verwarming
    cards:
      - type: entities
        title: temperaturen
        entities:
          - sensor.temperature_living
          - sensor.temperature_setpoint_living
          - input_number.slider_day
          - input_number.slider_night
          - input_number.slider1
      - type: entities
        title: bathroom
        entities:
          - binary_sensor.heater_status
          - switch.handdoekdroger_manueel
          - automation.handdoekdroger_automatisch
      - type: history-graph
        title: 'living temperature'
        entities:
          - sensor.temperature_setpoint_living
          - sensor.temperature_living
        hours_to_show: 72
        refresh_interval: 600
      - type: entities
        title: automations
        entities:
          - automation.heating_off_when_turning_alarm_on
          - automation.heating_on_when_turning_alarm_off
          - automation.read_ebus
  #        - automation.set_temp_high_when_being_home_weekend
  #        - automation.set_temp_high_when_being_home_workday
          - automation.set_temp_low_when_leaving_house
          - automation.wakup_turn_heating_up_weekday
          - automation.wakup_turn_heating_up_saturday
          - automation.wakup_turn_heating_up_sunday
      - type: history-graph
        title: 'heater setpunt'
        entities:
          - sensor.temperature_flow_radiator
        hours_to_show: 72
        refresh_interval: 600
  - title: Aanwezigheid
    cards:
      - type: glance
        title: aanwezigheid
        entities:
          - device_tracker.7c_7d_3d_ba_ef_be
          - sensor.alarm_state
  - title: media
    cards:
      - type: media-control
        entity: media_player.kodi_libreelec_local
      - type: media-control
        entity: media_player.living_main
