title: My Awesome Home
views:
    # View tab title.
  - title: Highlights
    icon: mdi:home
    cards:
    - type: entity
      entity: input_number.mailboxfull
      icon: mdi:mailbox
      name: Post Box
    - type: horizontal-stack
      cards:
        - type: sensor
          entity: sensor.temperature_setpoint_living
          name: temperature setpoint
        - type: sensor
          entity: sensor.temperature_living
          name: temperature living
    - type: horizontal-stack
      title: Solar panels
      cards:
        - type: entity
          entity: sensor.solaredge_energy_today
          unit: Wh
        - type: gauge
          entity: sensor.solaredge_current_power
          name: 'Solar power'
          min: 0
          max: 3000
  - title: Heating
    icon: mdi:radiator
    cards:
      - type: entities
        title: Living
        entities:
          - sensor.temperature_setpoint_living
          - sensor.temperature_living
          - input_boolean.turn_heating_on
          - switch.ventilator_control
          - input_number.slider_day
          - input_number.slider_night
          - input_number.slider1
          - sensor.temperature_flow_radiator
      - type: entities
        title: Badkamer
        entities:
          - switch.handdoekdroger_control
      - type: history-graph
        title: 'heater setpunt'
        entities:
          - sensor.temperature_flow_radiator
        hours_to_show: 72
        refresh_interval: 600
  - title: Temperatures
    icon: mdi:thermometer
    cards:
      - type: entities
        title: Temperatures
        entities:
          - sensor.temperature_living
          - sensor.temperature_bathroom
          - sensor.temperature_slaapkamer
          - sensor.temperature_zolder
      - type: history-graph
        title: 'living temperature'
        entities:
          - sensor.temperature_setpoint_living
          - sensor.temperature_living
        hours_to_show: 72
        refresh_interval: 600
      - type: history-graph
        title: 'temp kamers'
        entities:
          - sensor.temperature_bathroom
          - sensor.temperature_slaapkamer
        hours_to_show: 72
        refresh_interval: 600
      - type: sensor
        entity: sensor.temperature_living
        graph: line
        detail: 2
        hours_to_show: 72
      - type: sensor
        entity: sensor.temperature_zolder
        graph: line
        detail: 2
        hours_to_show: 72
  - title: Weather
    icon: mdi:weather-sunny
    cards:
        # The markdown card will render markdown text.
      - type: entities
        title: Weersvoorspelling
        entities:
          - sensor.br_detailed_condition
          - sensor.br_ground_temperature
          - sensor.br_temperature
          - sensor.br_precipitation
          - sensor.br_precipitation_forecast_average
          - sensor.br_rain_1d
          - sensor.br_wind_speed
          - sensor.br_wind_direction
      - type: iframe
        url: https://weerdata.weerslag.nl/image/1.0/?size=ani-forecast-550x550&type=Freecontent&v=14487341
        aspect_ratio: 100%
        title: Buien
      - type: iframe
        url: https://pollennieuws.nl/weerkaart/be-320kaart-website.png
        aspect_ratio: 100%
        title: Pollen
  - title: lights
    icon: mdi:lightbulb
    cards:
      - type: entities
        title: Living
        entities:
          - light.tradfri_bulb_2
          - light.tradfri_bulb_3
          - light.tradfri_bulb_5
          - light.tradfri_bulb_8
      - type: entities
        title: tuinverlichting
        entities:
          - switch.verlichting_terras
  - title: gras robot
    icon: mdi:ladybug
    cards:
      - type: entities
        title: Gras robot control
        entities:
          - binary_sensor.robot_status
          - switch.robomow_control
      - type: entities
        title: Energy and power
        entities:
          - sensor.robot_energy_today
          - sensor.robot_total_energy
          - sensor.robot_energy_start
          - sensor.robot_power
      - type: history-graph
        title: 'Power'
        entities:
          - sensor.robot_power
        hours_to_show: 72
        refresh_interval: 600
      - type: history-graph
        title: 'Energy'
        entities:
          - sensor.robot_total_energy
        hours_to_show: 72
        refresh_interval: 600
  - title: switches
    icon: mdi:toggle-switch
    cards:
      - type: entities
        title: schakelaars
        entities:
          - switch.s20_control
          - switch.s26_control
  - title: media
    icon: mdi:television-classic
    cards:
      - type: media-control
        entity:  media_player.living_room_main
      - type: entities
        title: Bluetooth speaker
        entities:
          - input_boolean.start_bluetooth_speaker
          - input_boolean.pause_bluetooth_speaker
          - input_boolean.resume_bluetooth_speaker
      - type: media-control
        entity:  media_player.living_room_tv
  - title: commute
    icon: mdi:car
    cards:
      - type: entities
        entities:
          - sensor.commute
  - title: Presence
    icon: mdi:human-male-female
    cards:
      - type: glance
        title: aanwezigheid
        entities:
          - binary_sensor.alarm_state
      - type: glance
        title: Post
        entities:
          - input_number.mailboxfull
          - sensor.mailbox
  - title: humidity
    icon: mdi:water-percent
    cards:
      - type: entities
        title: humidity
        entities:
          - sensor.humidity_zolder
          - sensor.humidity_bathroom
          - sensor.humidity_slaapkamer
      - type: entities
        title: water level
        entities:
          - sensor.water_level_current
          - sensor.water_level_voltage
      - type: history-graph
        title: 'water level'
        entities:
          - sensor.water_level_current
        hours_to_show: 8760
        refresh_interval: 600
      - type: history-graph
        title: 'waterniveau'
        entities:
          - sensor.waterlevel
        hours_to_show: 8760
        refresh_interval: 600
  - title: zon
    icon: mdi:solar-panel
    cards:
      - type: entities
        title: energy
        entities:
          - sensor.solaredge_energy_today
          - sensor.solaredge_energy_this_month
          - sensor.solaredge_energy_this_year
      - type: entities
        title: inverter
        entities:
          - sensor.solaredge_current_power
          - sensor.solaredge_energy_today
      - type: history-graph
        title: 'solar power'
        entities:
          - sensor.solaredge_current_power
        hours_to_show: 168
        refresh_interval: 600
      - type: history-graph
        title: 'solar energy'
        entities:
          - sensor.solaredge_energy_today
        hours_to_show: 8760
        refresh_interval: 600
  - title: k8400
    icon: mdi:printer-3d
    cards:
      - type: iframe
        url: http://192.168.0.209:8080/?action=stream
        aspect_ratio: 100%
      - type: entity
        entity: input_number.k8400_state
        name: 3d printer
      - type: horizontal-stack
        cards:
          - type: entity
            entity: input_number.k8400_printtime_elapsed
            name: time elapsed
          - type: entity
            entity: input_number.k8400_printtime_left
            name: time left
      - type: horizontal-stack
        cards:
          - type: entity
            entity: input_number.k8400_tool0_temperature
            name: temp extruder 1
          - type: entity
            entity: input_number.k8400_bed_temperature
            name: temp bed
      - type: horizontal-stack
        cards:
          - type: entity
            entity: input_select.led_printer