title: My Awesome Home
views:
    # View tab title.
  - title: Heating
    icon: mdi:radiator
    cards:
      - type: entities
        title: Living
        entities:
          - sensor.temperature_setpoint_living
          - sensor.temperature_living
          - input_boolean.turn_heating_on
          - switch.ventilator_control
          - input_number.slider_day
          - input_number.slider_night
          - input_number.slider1
          - sensor.temperature_flow_radiator
      - type: entities
        title: Badkamer
        entities:
          - switch.handdoekdroger_control
      - type: entities
        title: automations
        entities:
          - automation.handdoekdroger_automatisch
          - automation.start_ventilator_radiator
          - automation.stop_ventilator_radiator
          - automation.heating_off_when_turning_alarm_on
          - automation.heating_on_when_turning_alarm_off
          - automation.read_ebus
  #        - automation.set_temp_high_when_being_home_weekend
  #        - automation.set_temp_high_when_being_home_workday
          # - automation.set_temp_low_when_leaving_house
          # - automation.wakup_turn_heating_up_weekday
          # - automation.wakup_turn_heating_up_saturday
          # - automation.wakup_turn_heating_up_sunday
      - type: history-graph
        title: 'heater setpunt'
        entities:
          - sensor.temperature_flow_radiator
        hours_to_show: 72
        refresh_interval: 600
  - title: Temperatures
    icon: mdi:thermometer
    cards:
      - type: entities
        title: Temperatures
        entities:
          - sensor.temperature_living
          - sensor.temperature_bathroom
          - sensor.temperature_slaapkamer
          - sensor.temperature_zolder
      - type: history-graph
        title: 'living temperature'
        entities:
          - sensor.temperature_setpoint_living
          - sensor.temperature_living
        hours_to_show: 72
        refresh_interval: 600
      - type: history-graph
        title: 'temp kamers'
        entities:
          - sensor.temperature_bathroom
          - sensor.temperature_slaapkamer
        hours_to_show: 72
        refresh_interval: 600
      - type: sensor
        entity: sensor.temperature_living
        graph: line
        detail: 2
        hours_to_show: 72
      - type: sensor
        entity: sensor.temperature_zolder
        graph: line
        detail: 2
        hours_to_show: 72
  - title: lights
    icon: mdi:lightbulb
    cards:
      - type: entities
        title: Living
        entities:
          - light.tradfri_bulb
          - light.tradfri_bulb_2
          - light.tradfri_bulb_3
          - light.tradfri_bulb_4
      - type: entities
        title: tuinverlichting
        entities:
          - switch.verlichting_terras
  - title: Weather
    icon: mdi:weather-sunny
    cards:
        # The markdown card will render markdown text.
      - type: entities
        title: Weersvoorspelling
        entities:
          - sensor.br_detailed_condition
          - sensor.br_ground_temperature
          - sensor.br_temperature
          - sensor.br_precipitation
          - sensor.br_precipitation_forecast_average
          - sensor.br_rain_1d
          - sensor.br_wind_speed
          - sensor.br_wind_direction
      - type: iframe
        url: https://weerdata.weerslag.nl/image/1.0/?size=ani-forecast-550x550&type=Freecontent&v=14487341
        aspect_ratio: 140%
        title: Buien
  - title: gras robot
    icon: mdi:ladybug
    cards:
      - type: entities
        title: Gras robot control
        entities:
          - binary_sensor.robot_status
          - switch.robomow_control
      - type: entities
        title: Energy and power
        entities:
          - sensor.robot_energy_today
          - sensor.robot_total_energy
          - sensor.robot_energy_start
          - sensor.robot_power
      - type: history-graph
        title: 'Power'
        entities:
          - sensor.robot_power
        hours_to_show: 72
        refresh_interval: 600
      - type: history-graph
        title: 'Energy'
        entities:
          - sensor.robot_total_energy
        hours_to_show: 72
        refresh_interval: 600
  - title: switches
    icon: mdi:toggle-switch
    cards:
      - type: entities
        title: schakelaars
        entities:
          - switch.s20_control
          - switch.s26_control
  - title: media
    icon: mdi:television-classic
    cards:
      - type: media-control
        entity:  media_player.living_room_main
      - type: entities
        title: Bluetooth speaker
        entities:
          - input_boolean.start_bluetooth_speaker
          - input_boolean.pause_bluetooth_speaker
          - input_boolean.resume_bluetooth_speaker
      - type: media-control
        entity:  media_player.living_room_tv
  - title: commute
    icon: mdi:car
    cards:
      - type: entities
        entities:
          - sensor.commute
  - title: corona
    cards:
      - type: entities
        entities:
          - sensor.belgium_coronavirus_recovered
          - sensor.belgium_coronavirus_deaths
          - sensor.belgium_coronavirus_current
          - sensor.belgium_coronavirus_confirmed
      - type: entities
        entities:
          - sensor.worldwide_coronavirus_confirmed
          - sensor.worldwide_coronavirus_deaths
          - sensor.worldwide_coronavirus_current
          - sensor.worldwide_coronavirus_confirmed
      - type: history-graph
        entities:
          - sensor.belgium_coronavirus_deaths
        hours_to_show: 96
      - type: history-graph
        entities:
          - sensor.belgium_coronavirus_confirmed
        hours_to_show: 96
  - title: Presence
    icon: mdi:human-male-female
    cards:
      - type: glance
        title: aanwezigheid
        entities:
          - binary_sensor.alarm_state
  - title: humidity
    icon: mdi:water-percent
    cards:
      - type: entities
        title: humidity
        entities:
          - sensor.humidity_zolder
          - sensor.humidity_bathroom
          - sensor.humidity_slaapkamer
      - type: entities
        title: water level
        entities:
          - sensor.water_level
          - sensor.waterlevel
      - type: history-graph
        title: 'water level'
        entities:
          - sensor.water_level
        hours_to_show: 8760
        refresh_interval: 600
      - type: history-graph
        title: 'waterniveau'
        entities:
          - sensor.waterlevel
        hours_to_show: 8760
        refresh_interval: 600
